#!/bin/bash
# Program:
# 
# History:
# ${DATE}    ${USER}  First release
# EXTERNAL PARTIONED BY CLUSTERED BY SORTED BY ROW FORMAT DELIMITED
# FIELDS TERMINATED BY COLLECTION ITEMS TERMINATED BY MAP KEYS TERMINATED BY
# STORED AS SEQUENCEFILE RCFILE TEXTFILE LOCATION BUCKETS
# INPUTFORMAT OUTPUTFORMAT STRING BIGINT
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH